"""Every URDF-lowered collision primitive holds its whole link, with its declared headroom.

``urdf_lowering.lower_link_geometry`` fits each link's capsule to the link's
``<collision>`` **and** ``<visual>`` geometry and grows it by
``CAPSULE_HEADROOM_M``. This pins that property on the manifests as written
(4-dp rendering included), not on the in-memory fit: every vertex of every
collision and visual geometry of every link sits inside the committed primitive
by at least half the declared headroom.

Why the visual geometry counts: the vendor ``<collision>`` blocks under-cover
the parts they stand for. Measured before this check existed (hazard-log
Entry 046): H1's placeholder primitives left its torso mesh 549 mm outside the
kernel's capsule, G1's shoulder cylinders 61 mm, SO-100's servo housings 15 mm,
Flexiv Rizon 4's 30-vertex meshes 3.3 mm
(``docs/reference/collision-geometry-review.md``).

Real fixtures only (CLAUDE.md §1.11): the committed manifests, their URDFs and
the upstream meshes through ``robot_descriptions``. Complements
``test_collision_geometry_enclosure.py`` (the MJCF-fitted robots).
"""

from __future__ import annotations

from pathlib import Path

import numpy as np
import pytest

pytest.importorskip("yourdfpy")
pytest.importorskip("trimesh")
pytest.importorskip("robot_descriptions")

from openral_core import RobotDescription
from openral_core.assets import resolve_asset
from openral_core.schemas import CapsuleShape, SphereShape
from openral_safety.urdf_lowering import (
    CAPSULE_HEADROOM_M,
    _apply,
    _collision_local_vertices,
    _load_urdf,
    _origin_matrix,
)

_REPO = Path(__file__).resolve().parents[2]
# The robots whose `collision_geometry` is generated by the URDF lowering.
URDF_LOWERED = ("franka_panda", "g1", "h1", "rizon4", "so100_follower", "ur10e", "ur5e")


def _rpy(r: float, p: float, y: float) -> np.ndarray:
    cr, sr, cp, sp, cy, sy = np.cos(r), np.sin(r), np.cos(p), np.sin(p), np.cos(y), np.sin(y)
    rz = np.array([[cy, -sy, 0.0], [sy, cy, 0.0], [0.0, 0.0, 1.0]])
    ry = np.array([[cp, 0.0, sp], [0.0, 1.0, 0.0], [-sp, 0.0, cp]])
    rx = np.array([[1.0, 0.0, 0.0], [0.0, cr, -sr], [0.0, sr, cr]])
    return rz @ ry @ rx


def primitive_signed_distance(
    shape: object, origin: tuple[float, ...], pts: np.ndarray
) -> np.ndarray:
    """Signed distance of link-frame points to a capsule/sphere placed at ``origin``."""
    assert isinstance(shape, CapsuleShape | SphereShape), shape
    half = shape.length_m / 2.0 if isinstance(shape, CapsuleShape) else 0.0
    rot = _rpy(*origin[3:])
    local = (pts - np.asarray(origin[:3])) @ rot
    z = np.clip(local[:, 2], -half, half)
    closest = np.zeros_like(local)
    closest[:, 2] = z
    return np.linalg.norm(local - closest, axis=1) - shape.radius_m


@pytest.mark.parametrize("robot_id", URDF_LOWERED)
def test_every_link_vertex_is_inside_its_primitive_with_headroom(robot_id: str) -> None:
    manifest = _REPO / "robots" / robot_id / "robot.yaml"
    robot = RobotDescription.from_yaml(str(manifest))
    urdf = resolve_asset(robot.assets.urdf.ref, "urdf", manifest_dir=manifest.parent)  # type: ignore[union-attr]  # reason: every URDF_LOWERED robot declares assets.urdf
    model = _load_urdf(str(urdf))
    handler = model._filename_handler  # type: ignore[attr-defined]  # reason: yourdfpy URDF
    worst: list[tuple[float, str]] = []
    for geom in robot.collision_geometry:
        link = model.link_map[geom.link_name]  # type: ignore[attr-defined]  # reason: yourdfpy URDF
        elements = list(link.collisions or []) + list(link.visuals or [])
        assert elements, f"{geom.link_name}: no URDF geometry to check against"
        clouds = []
        for el in elements:
            verts = _collision_local_vertices(el, handler)
            assert verts is not None, f"{robot_id}/{geom.link_name}: a geometry did not load"
            clouds.append(_apply(_origin_matrix(el.origin), verts))
        sd = primitive_signed_distance(geom.shape, geom.origin_xyz_rpy, np.vstack(clouds))
        worst.append((float(sd.max()), geom.link_name))
    deepest_miss, link = max(worst)
    # The 4-dp rendering moves a primitive by ~0.1 mm at most; half the declared
    # headroom is the floor every committed primitive must still keep.
    assert deepest_miss <= -CAPSULE_HEADROOM_M / 2, (
        f"{robot_id}/{link}: a vertex sits {deepest_miss * 1e3:+.2f} mm from the primitive's "
        f"surface (must be <= {-CAPSULE_HEADROOM_M / 2 * 1e3:.2f} mm)"
    )
