"""Re-lowering a hand-tightened collision model must not quietly loosen it.

``urdf_lowering.lower_link_geometry`` PCA-fits a bounding capsule to any mesh
``<collision>``. That is the right default for onboarding a robot nobody has
measured — every mesh vertex is inside the result — but it is much looser than a
hand-fitted oriented box, and three committed manifests carry hand-fitted boxes
precisely because someone did the measuring:

* ``panda_mobile`` / ``panda_mobile_vslam`` — converted from capsules to boxes in
  #103;
* ``so101_follower`` — a hand base box.

Nothing stopped ``openral collision lower --write`` from replacing all of it. The
writer stamps the block ``# GENERATED by `openral collision lower``` and the
fleet drift guard (``test_collision_lowering_fleet``) then checks those manifests
**ACM-only**, so the regression would not have been caught there either: the diff
would show capsules replacing boxes, and nothing would say that the capsules
enclose up to 5x the volume.

This file is the pin. It asserts, on the real manifests and the real lowering,
that the committed geometry is the **tighter** one — so the day a re-lower is
committed, these tests fail — and that ``lower --write`` refuses the swap.

Real manifests, real URDF lowering, no mocks (CLAUDE.md §1.11). Gated on the
``[lowering]`` group (yourdfpy + robot_descriptions), like every other test that
drives the lowering tool.
"""

from __future__ import annotations

import shutil
from pathlib import Path

import pytest

pytest.importorskip("yourdfpy")

from openral_cli.collision import (
    _lowered_text,
    collision_primitive_envelope,
    geometry_loosening,
)
from openral_cli.main import app
from openral_core import BoxShape, CapsuleShape, RobotDescription, SphereShape
from typer.testing import CliRunner

runner = CliRunner()

# Manifests whose `collision_geometry` is hand-fitted (no `# GENERATED` header)
# AND whose links the URDF path would regenerate. `openarm` is hand-fitted too
# but is MJCF-sourced, so the tool reuses its geometry instead of re-deriving it
# and there is nothing to compare.
_HAND_TIGHTENED = ("panda_mobile", "so101_follower")


def _copy_manifest(name: str, tmp_path: Path) -> Path:
    """A hermetic copy of ``robots/<name>/`` — manifest plus any ``file:`` assets.

    ``--write`` must never be pointed at the committed tree, and the SRDF is
    resolved relative to the manifest, so it travels with it.
    """
    src = Path("robots") / name
    dst = tmp_path / "robot.yaml"
    shutil.copy(src / "robot.yaml", dst)
    for extra in sorted(src.glob("*.srdf")):
        shutil.copy(extra, tmp_path / extra.name)
    return dst


def _lowering(manifest: Path) -> tuple[str, str, list[object]]:
    try:
        return _lowered_text(manifest, acm_only=False, geometry_only=False)  # type: ignore[return-value]  # reason: the third element is list[GeometryLoosening]
    except (ValueError, FileNotFoundError) as exc:
        pytest.skip(f"{manifest}: {exc}")


# ── the envelope measurement itself ───────────────────────────────────────────


def test_envelope_is_the_closed_form_for_each_primitive_kind() -> None:
    """Volume and circumradius, checked against the formulae by hand.

    The guard's whole verdict rests on these two numbers, so they are pinned
    directly rather than only through the manifests that consume them.
    """
    import math

    volume, circ = collision_primitive_envelope(BoxShape(half_extents_m=(0.1, 0.2, 0.3)))
    assert volume == pytest.approx(8 * 0.1 * 0.2 * 0.3)
    assert circ == pytest.approx(math.sqrt(0.01 + 0.04 + 0.09))

    volume, circ = collision_primitive_envelope(SphereShape(radius_m=0.25))
    assert volume == pytest.approx(4 / 3 * math.pi * 0.25**3)
    assert circ == pytest.approx(0.25)

    volume, circ = collision_primitive_envelope(CapsuleShape(radius_m=0.1, length_m=0.4))
    assert volume == pytest.approx(math.pi * 0.01 * 0.4 + 4 / 3 * math.pi * 0.001)
    assert circ == pytest.approx(0.3)


def test_a_link_the_lowering_drops_counts_as_loosening() -> None:
    """Losing a link's primitive outright is the worst version of the same failure.

    A link with no entry is invisible to the kernel's collision check, so a
    lowering that emits nothing for a link the manifest covers must not read as
    "no change".
    """
    shipped = list(RobotDescription.from_yaml("robots/panda_mobile/robot.yaml").collision_geometry)
    assert shipped, "panda_mobile must carry collision geometry for this test to mean anything"

    findings = geometry_loosening(shipped, [])

    assert {f.link_name for f in findings} == {g.link_name for g in shipped}
    assert all(f.lowered == "" for f in findings)


# ── the manifests ─────────────────────────────────────────────────────────────


@pytest.mark.parametrize("robot_name", _HAND_TIGHTENED)
def test_shipped_geometry_is_tighter_than_a_re_lower(robot_name: str) -> None:
    """The committed primitives must stay the tighter ones.

    Reads backwards on purpose: it asserts that re-lowering *would* loosen the
    manifest. That is the pin — the assertion holds only while the committed
    geometry is hand-fitted, and fails the moment someone commits the tool's
    output over it, which is exactly the regression this file exists to catch.
    """
    _current, _spliced, loosening = _lowering(Path("robots") / robot_name / "robot.yaml")

    assert loosening, (
        f"{robot_name}'s collision_geometry now matches (or is looser than) what "
        "`openral collision lower` emits. If the manifest was regenerated, the "
        "hand-fitted boxes have been replaced by PCA capsules and the kernel's "
        "collision model just got looser — revert the geometry block. If the "
        "lowering itself was improved to emit tight primitives, delete this "
        "parametrization entry and say so in the PR."
    )
    # Every reported link must be strictly looser on at least one axis, and the
    # magnitudes are recorded so a future reader sees the size of what is guarded.
    assert all(f.volume_ratio > 1.0 or f.circumradius_ratio > 1.0 for f in loosening)


def test_panda_mobile_relower_would_inflate_every_arm_link() -> None:
    """The specific hazard #157 flagged, measured link by link.

    ``panda_mobile``'s kernel collision model is ``panda_link1..7`` and nothing
    else, so "every arm link" is the whole model: a re-lower would loosen all of
    it at once, not a corner of it.
    """
    _current, _spliced, loosening = _lowering(Path("robots/panda_mobile/robot.yaml"))

    assert {f.link_name for f in loosening} == {f"panda_link{i}" for i in range(1, 8)}
    assert min(f.volume_ratio for f in loosening) > 1.5
    assert min(f.circumradius_ratio for f in loosening) > 1.25


@pytest.mark.parametrize("robot_name", ["franka_panda", "ur5e"])
def test_a_tool_generated_manifest_is_not_flagged(robot_name: str) -> None:
    """No false positives: the guard must not block the ordinary onboarding path.

    These manifests already equal the tool's output. The comparison happens at
    the precision ``render_blocks`` writes at, so a committed 4-dp value must not
    read as "tighter" than the full-precision fit it was rounded from — which it
    does if the two sides are compared raw.
    """
    _current, _spliced, loosening = _lowering(Path("robots") / robot_name / "robot.yaml")

    assert loosening == [], (
        f"{robot_name} is tool-generated and must compare equal; "
        f"got {[(f.link_name, f.volume_ratio) for f in loosening]}"
    )


# ── the CLI refusal ───────────────────────────────────────────────────────────


def test_lower_write_refuses_and_leaves_the_manifest_untouched(tmp_path: Path) -> None:
    """`--write` must refuse the swap, and must not half-apply it."""
    dst = _copy_manifest("panda_mobile", tmp_path)
    before = dst.read_bytes()

    result = runner.invoke(app, ["collision", "lower", "--robot", str(dst), "--write"])

    assert result.exit_code == 3, result.output
    assert dst.read_bytes() == before, "a refused lower must not modify the manifest"
    assert "Refusing to loosen" in result.output
    assert "panda_link6" in result.output
    # The remedy is stated, and it is not a flag.
    assert "no override flag" in result.output


def test_lower_dry_run_reports_the_loosening_the_diff_cannot_show(tmp_path: Path) -> None:
    """A dry run still says it, because the diff alone does not.

    Reading `- box h=[...]` / `+ capsule r=... L=...` by eye does not tell anyone
    that the capsule encloses 3.7x the volume. If the warning only appeared on
    `--write`, a reviewer approving the diff would never see it.
    """
    dst = _copy_manifest("panda_mobile", tmp_path)

    result = runner.invoke(app, ["collision", "lower", "--robot", str(dst)])

    assert result.exit_code == 0, result.output
    assert "Refusing to loosen" in result.output
    assert "volume x" in result.output


def test_acm_only_lower_still_writes(tmp_path: Path) -> None:
    """The guard is scoped to the geometry block it protects.

    ``--acm-only`` regenerates the allowed-collision matrix and leaves geometry
    alone, so there is no swap to refuse — and this is the flag the fleet drift
    guard uses on exactly these manifests.
    """
    dst = _copy_manifest("panda_mobile", tmp_path)

    result = runner.invoke(
        app, ["collision", "lower", "--robot", str(dst), "--acm-only", "--write"]
    )

    assert result.exit_code == 0, result.output
    assert "Refusing to loosen" not in result.output
