"""Every URDF-lowered link's primitive set holds its whole link, with its declared headroom.

``urdf_lowering.lower_link_geometry`` fits each link's primitives (one capsule,
one box or a capsule chain) to the link's ``<collision>`` **and** ``<visual>``
geometry and grows them by ``CAPSULE_HEADROOM_M``. This pins that property on
the manifests as written (4-dp rendering included), not on the in-memory fit:
every vertex of every collision and visual geometry of every link sits inside
the union of the committed primitives by at least half the declared headroom.

Why the visual geometry counts: the vendor ``<collision>`` blocks under-cover
the parts they stand for. Measured before this check existed (hazard-log
Entry 046): H1's placeholder primitives left its torso mesh 549 mm outside the
kernel's capsule, G1's shoulder cylinders 61 mm, SO-100's servo housings 15 mm,
Flexiv Rizon 4's 30-vertex meshes 3.3 mm
(``docs/reference/collision-geometry-review.md``).

Real fixtures only (CLAUDE.md §1.11): the committed manifests, their URDFs and
the upstream meshes through ``robot_descriptions``. Complements
``test_collision_geometry_enclosure.py`` (the MJCF-fitted robots).
"""

from __future__ import annotations

from pathlib import Path

import numpy as np
import pytest

pytest.importorskip("yourdfpy")
pytest.importorskip("trimesh")
pytest.importorskip("robot_descriptions")

import trimesh
from openral_core import RobotDescription
from openral_core.assets import resolve_asset
from openral_core.schemas import (
    TIGHT_CONTAINMENT_EPSILON_M,
    BoxShape,
    CapsuleShape,
    LinkCollisionGeometry,
    SphereShape,
)
from openral_safety.urdf_lowering import (
    CAPSULE_HEADROOM_M,
    _collision_local_mesh,
    _load_urdf,
    _origin_matrix,
)

from tests.unit._collision_kernel_verdict import (
    surface_pieces,
    tight_escape_m,
    tight_escape_per_point_m,
)

_REPO = Path(__file__).resolve().parents[2]
# The robots whose `collision_geometry` is generated by the URDF lowering.
URDF_LOWERED = ("franka_panda", "g1", "h1", "rizon4", "so100_follower", "ur10e", "ur5e")


def _static_links() -> list[tuple[str, str]]:
    """``(robot, link)`` for every static link a manifest declares, discovered, not listed.

    A static link is a ``fixed_attachments`` child that carries
    ``collision_geometry`` on a robot lowered from its MJCF, and is a link of the
    robot's own vendored URDF — where ``urdf_lowering._static_link_meshes`` takes
    its geometry from (the MJCF twin has no body to hold it to). The MJCF-mapped
    pedestals (OpenArm's ``*_link0``, the URDF's ``*_base_link``) are not URDF
    link names, so they fall out.
    """
    import xml.etree.ElementTree as ET

    found = []
    for manifest in sorted(_REPO.glob("robots/*/robot.yaml")):
        robot_id = manifest.parent.name
        if robot_id in URDF_LOWERED:
            continue
        robot = RobotDescription.from_yaml(str(manifest))
        urdf = robot.assets.urdf
        if not robot.assets.mjcf or urdf is None or not urdf.ref.startswith("file:"):
            continue
        urdf_links = {
            el.attrib.get("name")
            for el in ET.parse(manifest.parent / urdf.ref.removeprefix("file:"))
            .getroot()
            .iter("link")
        }
        geom_links = {g.link_name for g in robot.collision_geometry}
        found += [
            (robot_id, a.child_link)
            for a in robot.fixed_attachments
            if a.child_link in geom_links and a.child_link in urdf_links
        ]
    return found


# Static links: `fixed_attachments` children an MJCF-lowered robot takes from its URDF.
STATIC_LINKS = _static_links()


def test_the_static_link_discovery_finds_the_openarm_torso() -> None:
    """Guard against the discovery silently finding nothing (the test would then be vacuous)."""
    assert ("openarm", "openarm_body_link0") in STATIC_LINKS


def _rpy(r: float, p: float, y: float) -> np.ndarray:
    cr, sr, cp, sp, cy, sy = np.cos(r), np.sin(r), np.cos(p), np.sin(p), np.cos(y), np.sin(y)
    rz = np.array([[cy, -sy, 0.0], [sy, cy, 0.0], [0.0, 0.0, 1.0]])
    ry = np.array([[cp, 0.0, sp], [0.0, 1.0, 0.0], [-sp, 0.0, cp]])
    rx = np.array([[1.0, 0.0, 0.0], [0.0, cr, -sr], [0.0, sr, cr]])
    return rz @ ry @ rx


def primitive_signed_distance(
    shape: object, origin: tuple[float, ...], pts: np.ndarray
) -> np.ndarray:
    """Signed distance of link-frame points to a capsule/sphere/box placed at ``origin``."""
    rot = _rpy(*origin[3:])
    local = (pts - np.asarray(origin[:3])) @ rot
    if isinstance(shape, BoxShape):
        q = np.abs(local) - np.asarray(shape.half_extents_m)
        return np.linalg.norm(np.maximum(q, 0.0), axis=1) + np.minimum(q.max(axis=1), 0.0)
    assert isinstance(shape, CapsuleShape | SphereShape), shape
    half = shape.length_m / 2.0 if isinstance(shape, CapsuleShape) else 0.0
    z = np.clip(local[:, 2], -half, half)
    closest = np.zeros_like(local)
    closest[:, 2] = z
    return np.linalg.norm(local - closest, axis=1) - shape.radius_m


@pytest.mark.parametrize("robot_id", URDF_LOWERED)
def test_every_link_vertex_is_inside_its_primitive_with_headroom(robot_id: str) -> None:
    manifest = _REPO / "robots" / robot_id / "robot.yaml"
    robot = RobotDescription.from_yaml(str(manifest))
    urdf = resolve_asset(robot.assets.urdf.ref, "urdf", manifest_dir=manifest.parent)  # type: ignore[union-attr]  # reason: every URDF_LOWERED robot declares assets.urdf
    model = _load_urdf(str(urdf))
    handler = model._filename_handler  # type: ignore[attr-defined]  # reason: yourdfpy URDF
    by_link: dict[str, list[LinkCollisionGeometry]] = {}
    for geom in robot.collision_geometry:  # a link may carry several primitives
        by_link.setdefault(geom.link_name, []).append(geom)
    worst: list[tuple[float, str]] = []
    for link_name, geoms in by_link.items():
        link = model.link_map[link_name]  # type: ignore[attr-defined]  # reason: yourdfpy URDF
        elements = list(link.collisions or []) + list(link.visuals or [])
        assert elements, f"{link_name}: no URDF geometry to check against"
        parts = []
        for el in elements:
            part = _collision_local_mesh(el, handler)
            assert part is not None, f"{robot_id}/{link_name}: a geometry did not load"
            parts.append(part.apply_transform(_origin_matrix(el.origin)))
        mesh = trimesh.util.concatenate(parts)
        pts = np.asarray(mesh.vertices, dtype=float)
        # The surface, not just the vertices: a capsule chain is not convex, so a
        # triangle across its seam could leave the union with all corners inside.
        _, uncovered = surface_pieces(pts, np.asarray(mesh.faces), geoms)
        assert uncovered == 0, (
            f"{robot_id}/{link_name}: {uncovered} surface triangles leave the primitive union"
        )
        # Inside the union = inside the nearest primitive.
        sd = np.min([primitive_signed_distance(g.shape, g.origin_xyz_rpy, pts) for g in geoms], 0)
        worst.append((float(sd.max()), link_name))
        for g in geoms:  # a refined box: the mesh must sit inside its DOP and hull too
            if g.tight_geometry is not None:
                local = (pts - np.asarray(g.origin_xyz_rpy[:3])) @ _rpy(*g.origin_xyz_rpy[3:])
                escape = tight_escape_m(g, local)
                assert escape <= TIGHT_CONTAINMENT_EPSILON_M, (
                    f"{robot_id}/{link_name}: a vertex sits {escape * 1e3:.6f} mm outside "
                    "the declared tight_geometry"
                )
    deepest_miss, link = max(worst)
    # The 4-dp rendering moves a primitive by ~0.1 mm at most; half the declared
    # headroom is the floor every committed primitive must still keep.
    assert deepest_miss <= -CAPSULE_HEADROOM_M / 2, (
        f"{robot_id}/{link}: a vertex sits {deepest_miss * 1e3:+.2f} mm from the primitive's "
        f"surface (must be <= {-CAPSULE_HEADROOM_M / 2 * 1e3:.2f} mm)"
    )


@pytest.mark.parametrize(("robot_id", "link_name"), STATIC_LINKS)
def test_every_static_link_vertex_is_inside_its_primitives_with_headroom(
    robot_id: str, link_name: str
) -> None:
    """The committed entries of a URDF-sourced static link hold its whole geometry.

    The same three properties as the URDF-lowered links above, on the manifest as
    written: the surface inside the union of the boxes, every vertex at least half
    the declared headroom inside, and every vertex inside the refinement of at least
    one of the link's pieces (a link split into slabs puts each vertex in one slab's
    hull, not in all of them). Read through the lowering's own static-link reader.
    """
    from openral_core.assets import AssetFetchError
    from openral_core.exceptions import ROSConfigError
    from openral_safety.urdf_lowering import _static_link_meshes

    manifest = _REPO / "robots" / robot_id / "robot.yaml"
    robot = RobotDescription.from_yaml(str(manifest))
    # Every other fixed-attachment child counts as mapped, so only this link is read.
    others = {a.child_link: -1 for a in robot.fixed_attachments if a.child_link != link_name}
    try:
        mesh = _static_link_meshes(robot, others, manifest.parent)[link_name]
    except ROSConfigError as exc:
        if isinstance(exc.__cause__, AssetFetchError):
            pytest.skip(f"{robot_id}: description clone unavailable on this host: {exc}")
        raise
    geoms = [g for g in robot.collision_geometry if g.link_name == link_name]
    assert geoms, f"{robot_id}/{link_name}: the manifest carries no entry for it"
    pts = np.asarray(mesh.vertices, dtype=float)
    _, uncovered = surface_pieces(pts, np.asarray(mesh.faces), geoms)
    assert uncovered == 0, f"{robot_id}/{link_name}: {uncovered} surface triangles leave the union"
    sd = np.min([primitive_signed_distance(g.shape, g.origin_xyz_rpy, pts) for g in geoms], 0)
    assert float(sd.max()) <= -CAPSULE_HEADROOM_M / 2, (
        f"{robot_id}/{link_name}: a vertex sits {float(sd.max()) * 1e3:+.2f} mm from the union's "
        f"surface (must be <= {-CAPSULE_HEADROOM_M / 2 * 1e3:.2f} mm)"
    )
    escape = np.full(len(pts), np.inf)
    for g in geoms:
        if g.tight_geometry is None:
            continue
        local = (pts - np.asarray(g.origin_xyz_rpy[:3])) @ _rpy(*g.origin_xyz_rpy[3:])
        escape = np.minimum(escape, tight_escape_per_point_m(g, local))
    assert float(escape.max()) <= TIGHT_CONTAINMENT_EPSILON_M, (
        f"{robot_id}/{link_name}: a vertex sits {float(escape.max()) * 1e3:.6f} mm outside every "
        "piece's tight_geometry"
    )
